
import java.awt.Image;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brian
 */
public class Search extends javax.swing.JInternalFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        groupType();
        groupGender();
    }
    
    private ButtonGroup groupType(){
        ButtonGroup group = new ButtonGroup();
        group.add(typeDog);
        group.add(typeCat);
        group.add(typeAny);
        return group;
    }
 
    private ButtonGroup groupGender(){
        ButtonGroup group = new ButtonGroup();
        group.add(genderMale);
        group.add(genderFemale);
        group.add(genderAny);
        return group;
    }
    
    Connection connection;
    PreparedStatement preparedStatement;
    String path = null;
    byte[] animalImage = null;
    int retrieveId;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typeDog = new javax.swing.JRadioButton();
        typeCat = new javax.swing.JRadioButton();
        typeAny = new javax.swing.JRadioButton();
        genderMale = new javax.swing.JRadioButton();
        genderFemale = new javax.swing.JRadioButton();
        genderAny = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        buttonAdopt = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        matchType = new javax.swing.JLabel();
        matchGender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        matchName = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(800, 600));

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Gender");

        typeDog.setText("Dog");
        typeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeDogActionPerformed(evt);
            }
        });

        typeCat.setText("Cat");

        typeAny.setText("Any");

        genderMale.setText("Male");
        genderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderMaleActionPerformed(evt);
            }
        });

        genderFemale.setText("Female");

        genderAny.setText("Any");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(buttonSearch)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeDog, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderMale, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genderAny, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(typeAny, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeDog)
                    .addComponent(typeCat)
                    .addComponent(typeAny))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(genderMale)
                    .addComponent(genderFemale)
                    .addComponent(genderAny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(buttonSearch)
                .addGap(37, 37, 37))
        );

        buttonAdopt.setText("Adopt");
        buttonAdopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdoptActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Lucky Match");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Gender");

        photo.setBackground(new java.awt.Color(255, 255, 255));
        photo.setForeground(new java.awt.Color(255, 255, 255));
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonAdopt)
                        .addGap(86, 86, 86)
                        .addComponent(buttonCancel)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(104, 104, 104)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(matchName)
                                        .addComponent(matchType)
                                        .addComponent(matchGender)))
                                .addComponent(jLabel5)))
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(matchName))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(matchType))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(matchGender))
                .addGap(18, 18, 18)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdopt)
                    .addComponent(buttonCancel))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdoptActionPerformed
        Boolean availability = false;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost/animal_queue", "brian", "");
            preparedStatement = connection.prepareStatement("update animal set availability=? where id = ?");

            preparedStatement.setBoolean(1, availability);
            preparedStatement.setInt(2, retrieveId);
            preparedStatement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Congratulations on your new pet! Please come in to pick up your new pet.");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonAdoptActionPerformed

    private void typeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeDogActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.hide();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private String searchSQL(String search, String type, Boolean typeAny, String gender, Boolean genderAny) {
            
        if (typeAny && genderAny)                
            search = "select * from animal where availability = true order by id limit 1";
        else if (typeAny && "Male".equals(gender))
            search = "select * from animal where gender = 'Male' and availability = true order by id limit 1";
        else if (typeAny && "Female".equals(gender))
            search = "select * from animal where gender = 'Female' and availability = true order by id ";
        else if (genderAny && "Dog".equals(type))
            search = "select * from animal where type ='Dog' and availability = true order by id ";
        else if (genderAny && "Cat".equals(type))
            search = "select * from animal where type = 'Cat' and availability = true order by id";
        else if ("Male".equals(gender) && "Dog".equals(type))
            search = "select * from animal where gender = 'Male' and type = 'Dog' and availability = true order by id";
        else if ("Male".equals(gender) && "Cat".equals(type))
            search = "select * from animal where gender = 'Male' and type = 'Cat' and availability = true order by id";
        else if ("Female".equals(gender) && "Dog".equals(type))
            search = "select * from animal where gender = 'Female' and type = 'Dog' and availability = true order by id";
        else if ("Female".equals(gender) && "Cat".equals(type))
            search = "select * from animal where gender = 'Female' and type = 'Cat' and availability = true order by id";
            
        return search;
        }
            
    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        String gender = null;
        Boolean genderAny = false;
        if (genderMale.isSelected())
            gender = "Male";
        else if (genderFemale.isSelected())
            gender = "Female";
        else
            genderAny = true;
        
        String type = null;
        Boolean typeAny = false;
        if (typeDog.isSelected())
            type = "Dog";
        else if (typeCat.isSelected())
            type = "Cat";
        else
            typeAny = true;
        
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/animal_queue", "brian", "");
            Statement statement = connection.createStatement();
            ResultSet resultSet = null;
                        
            String str = null;
            String search = searchSQL(str, type, typeAny, gender, genderAny);
                
            resultSet = statement.executeQuery(search);               
            resultSet.next();
            String retrieveName = resultSet.getString("name");
            String retrieveType = resultSet.getString("type");
            String retrieveGender = resultSet.getString("gender");
            retrieveId = resultSet.getInt("id");
            
            matchName.setText(retrieveName.trim());
            matchType.setText(retrieveType);
            matchGender.setText(retrieveGender);

            Blob blob = resultSet.getBlob("photo");
            byte[] imageBytes = blob.getBytes(1,(int) blob.length());
            ImageIcon image = new ImageIcon(imageBytes);
            Image im = image.getImage();
            Image myImg = im.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(myImg);
   
            photo.setIcon(newImage);
            
            
        } catch (SQLException error) {
            //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, error);
            JOptionPane.showMessageDialog(null, "It looks like there are no pets left with this search. Please try a different search");
        }
        
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void genderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderMaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdopt;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JRadioButton genderAny;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel matchGender;
    private javax.swing.JLabel matchName;
    private javax.swing.JLabel matchType;
    private javax.swing.JLabel photo;
    private javax.swing.JRadioButton typeAny;
    private javax.swing.JRadioButton typeCat;
    private javax.swing.JRadioButton typeDog;
    // End of variables declaration//GEN-END:variables
}
